spring.application.name = tp-bibliobus

# Configuration JPA
spring.datasource.url = jdbc:mysql://localhost:3306/bibili
spring.datasource.username = root
spring.datasource.password = root

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
